org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false

minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.3.0
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

mod_id=rpstamina
mod_name=RP Stamina
mod_license=MIT
mod_version=1.0.2-1.20.1-forge
mod_group_id=faygolover.rpstamina
mod_authors=faygoLover
mod_description=Stamina system for RP servers: configurable drains, slow smooth regeneration, restoring items with tolerance, integration with RP Perks.
